version: '3.8'
services:
  db:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db-57xsl
      MYSQL_DATABASE: example
      MYSQL_HOST: db
      MYSQL_PASSWORD: db-57xsl
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - react-java-mysql
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/example
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: db-57xsl
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src/main/resources/application.properties:/backend/src/main/resources/application.properties
    networks:
      - react-java-mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - react-java-mysql
networks:
  react-java-mysql:
    driver: bridge
volumes:
  db_data: